# Generated by Django 4.2.2 on 2023-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="")),
                (
                    "blog_type",
                    models.CharField(
                        choices=[
                            ("1", "Sport"),
                            ("2", "Travel"),
                            ("3", "Handmade"),
                            ("4", "Funny Animals"),
                            ("5", "Nature"),
                        ],
                        default="4",
                        max_length=1,
                    ),
                ),
                ("creation_date", models.DateField()),
            ],
        ),
    ]
