# Generated by Django 4.2.2 on 2023-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_type', models.CharField(choices=[('1', 'Urgent'), ('2', 'Regular'), ('3', 'Low')], default='2', max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('create_data', models.DateField()),
                ('username', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
