# Generated by Django 4.2.2 on 2023-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_blog_blog_type_alter_blog_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="creation_date",
        ),
        migrations.AddField(
            model_name="blog",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
