# Generated by Django 4.2.2 on 2023-08-05 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_remove_blog_creation_date_blog_created_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="blog_type",
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_category",
            field=models.CharField(
                choices=[
                    ("1", "Travel"),
                    ("2", "Sport"),
                    ("3", "Nature"),
                    ("4", "Animals"),
                    ("5", "Food"),
                    ("6", "DIY and Crafts"),
                    ("7", "Science and Technology"),
                ],
                default="1",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="created_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=70),
        ),
    ]
