# Generated by Django 4.2.2 on 2023-08-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="media"
            ),
        ),
    ]
