# Generated by Django 4.2.4 on 2023-09-08 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_userprofile_city_alter_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
