# Generated by Django 4.2.2 on 2023-08-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Media"
            ),
        ),
    ]
