# Generated by Django 4.2.4 on 2023-09-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_userprofile'),
        ('core', '0006_remove_userprofile_website'),
    ]

    operations = [
    ]
