# Generated by Django 4.2 on 2023-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20230910_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.CharField(choices=[('1', 'Travel'), ('2', 'Sport'), ('3', 'Nature'), ('4', 'Animals'), ('5', 'Food'), ('6', 'DIY and Crafts'), ('7', 'Science and Technology'), ('8', 'Fashion'), ('9', 'Medicine'), ('10', 'Psychology'), ('11', 'Art')], default='1', max_length=2),
        ),
    ]
