# Generated by Django 4.2.4 on 2023-09-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_merge_20230910_2031"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
