# Generated by Django 4.2 on 2023-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
