# Generated by Django 4.2.2 on 2023-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.CharField(max_length=20)),
                ('about_text', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='Media')),
            ],
        ),
    ]
