# Generated by Django 4.2 on 2023-08-27 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_blog_category_alter_blog_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
