# Generated by Django 4.2.4 on 2023-08-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_blog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image1",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Media"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image2",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Media"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="image3",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="Media"
            ),
        ),
    ]
