# Generated by Django 4.2.4 on 2023-08-31 06:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_blog_image1_blog_image2_blog_image3"),
        ("core", "0014_blogcomment"),
    ]

    operations = []
