# Generated by Django 4.2.2 on 2023-08-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
